apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedelta-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedelta-scheduler
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "bindings", "pods/binding"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/status", "events"]
    verbs: ["get", "list", "watch", "patch", "create", "update"]
  - apiGroups: [""]
    resources: ["configmaps", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "csidrivers", "csistoragecapacities"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["topology.kubernetes.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedelta-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedelta-scheduler
subjects:
  - kind: ServiceAccount
    name: kubedelta-scheduler
    namespace: kube-system
